### ISSUE TITLE
Restrict room creation to specific users only

### ISSUE THREAD

**Issue by Simonx22** [crybapp/web#23]
So you can invite other people without them being able to create a room. They can only stay in the current room and if they leave, they get kicked out completely.

**Comment by darnfish** [comment]
This is cool, will work on this! Hopefully the admin panel @plusreed has been working on can make this easier, but for now I can add it as an option into `.env` 😄

**Comment by plusreed** [comment]
Just to add on to what @williamsthing said above ^^

In case anyone is wondering, the admin panel is closed source as of right now due to its unfinished state. It literally doesn't connect to anything Cryb and is just design mockups that do nothing at the moment.

We're working on getting this open source as soon as we get it in an actual working state. Plus, we need to actually make sure it actually works on all instances since it was made around when Cryb wasn't open source. :P

**Comment by jeda** [comment]
Added in crybapp/api@f9af736. Thanks for suggesting this!
