### ISSUE TITLE
Player keeps trying to start even if not allowed by the browser due to autoplay policy

### ISSUE THREAD

**Issue by jeda** [crybapp/web#29]
Experienced by Pantotone in Cryb Discord server.

![cannot play](https://cdn.discordapp.com/attachments/621226442608607252/634647850352902155/unknown.png)

We should ask for the user to interact with the page - and definitely not indefinitely try starting up stuff.

**Comment by darnfish** [comment]
We used to have a UI that handled this limit, it'd try play the stream, then if it couldn't due to this error it'd mute the stream and play again. Then it showed a custom popup that asked users to click a "Unmute" button which counted as enough user interaction so that the page could autoplay normally. There's more info on this limitation [here](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes), and I think compatibility changes browser-to-browser so I think having a cross-browser solution would be ideal!

I'll work on this soon unless someone else wants to take on this issue 😄

**Comment by jeda** [comment]
This got fixed already by me in 531f67f. Closing!
